# Generated by Django 4.2.11 on 2024-04-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee'),
        ),
    ]
