# Generated by Django 4.2.11 on 2024-04-07 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_user_product_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='employees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee'),
        ),
    ]
